In [1]:
#******************************Name**********************************
#-----------------------CAR SELLING PRICE PREDICTION-----------------------------

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

from joblib import dump,load

df=pd.read_csv("Car.csv")#IMPORTING CSV FILE FROM DIRECTORY
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0

In [2]:
#Finding out DATA TYPES.
print(df.dtypes)

print(df.index)

name              object
year               int64
selling_price      int64
km_driven          int64
fuel              object
seller_type       object
transmission      object
owner             object
mileage           object
engine            object
max_power         object
torque            object
seats            float64
dtype: object
RangeIndex(start=0, stop=8128, step=1)

In [3]:
# Checking for missing value.
df.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [4]:
#Dropping null(missing value) and unwanted column.
df = df.drop(columns=["torque"])
df=df.drop(columns=["name"])
df=df.dropna()
df

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,5.0
1,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,5.0
2,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,5.0
3,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,5.0
4,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,5.0
...,...,...,...,...,...,...,...,...,...,...,...
8123,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,5.0
8124,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,5.0
8125,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,5.0
8126,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,5.0
8127,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,5.0

In [5]:
#--------------------------PREPROCESSING---------------------------------------
#for removing kmpl and km/kg from mileage.
df['mileage']=df['mileage'].replace(' kmpl','',regex=True).str.replace(',', '')
df['mileage']=df['mileage'].replace(' km/kg','',regex=True).str.replace(',', '')
#for removing  and cc from engine.
df['engine']=df['engine'].replace(' CC','',regex=True).str.replace(',', '')
#for removing  and bhp from max_power.
df['max_power']=df['max_power'].replace(' bhp','',regex=True).str.replace(',', '')

In [6]:
#converting string into numeric
df['mileage'] = pd.to_numeric(df['mileage'])
df['engine'] = pd.to_numeric(df['engine'])
df['max_power'] = pd.to_numeric(df['max_power'])

#checking for null values again after removing some strings from the features
df.isnull().sum()

year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
mileage          0
engine           0
max_power        1
seats            0
dtype: int64

In [7]:
# dropping null value from max_power
df=df.dropna()

In [8]:
#***************Sperating Independent and Dependent data*******************

#Independent      
x=df.iloc[:,:]
x=x.drop(columns=["selling_price"])
#Dependent
y=df["selling_price"]

In [9]:
#----------------Encoding data-------------------------
from sklearn.preprocessing import LabelEncoder

la=LabelEncoder()
x['fuel']=la.fit_transform(x['fuel'])

lb=LabelEncoder()
x['seller_type']=lb.fit_transform(x['seller_type'])

lt=LabelEncoder()
x['transmission']=lt.fit_transform(x['transmission'])

lo=LabelEncoder()
x['owner']=lo.fit_transform(x['owner'])

In [10]:
#-------------scaling on Independent data.-----------------------
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [11]:
#-----------------training and testing data----------------------
# Splitting of training and testing data  
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
#Applying--------- (RandomForestRegressor)----------------------
from sklearn.ensemble import RandomForestRegressor
  
reg=RandomForestRegressor()
reg.fit(x_train,y_train)

RandomForestRegressor()

In [13]:
#-------------------prediction of data-----------------------------
y_pred=reg.predict(x_test)

In [14]:
#-----------------Checking accuracy using r2_score-------------------
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

0.975794908892089

In [15]:
#----------------Saving the data using joblib----------------------

dump(la,"fuel.joblib")
dump(lb,"seller_type.joblib")
dump(lt,"transmission.joblib")
dump(lo,"owner.joblib")
dump(sc,"scaling.joblib")
dump(reg,"regressor.joblib")

['regressor.joblib']